import { ApolloProvider } from "@apollo/client";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { ChakraProvider } from "@chakra-ui/react";
import type { AppProps } from "next/app";
import Head from "next/head";
import Layout from "../components/_layout/Layout";
import client from "../lib/apolloClient";

import { Signika } from "@next/font/google";
import theme from "../lib/chakra";

const font = Signika({ subsets: ["latin"] });

export default function App({ Component, pageProps }: AppProps) {
  return (
    <UserProvider>
      <ApolloProvider client={client}>
        <ChakraProvider theme={theme}>
          <Head>
            <title>Superstar Squad</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/logo.png" />
          </Head>
          <main className={font.className}>
            <Layout>
              <Component {...pageProps} />
            </Layout>
          </main>
        </ChakraProvider>
      </ApolloProvider>
    </UserProvider>
  );
}
