import { ApolloProvider } from "@apollo/client";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { ChakraProvider } from "@chakra-ui/react";
import type { AppProps } from "next/app";
import Head from "next/head";
import Layout from "../components/_layout/Layout";
import client from "../lib/apolloClient";
import { Signika } from "@next/font/google";
import theme from "../lib/chakra";
import { useRouter } from "next/router";
import { IntlProvider } from "react-intl";
import { getDirection, messages } from "../lang";
import { CacheProvider } from "@emotion/react";
import createCache from "@emotion/cache";
import rtl from "stylis-plugin-rtl";

const options = {
  rtl: { key: "css-he-il", stylisPlugins: [rtl] },
  ltr: { key: "css-en-us" },
};

const font = Signika({ subsets: ["latin"] });

export default function App({ Component, pageProps }: AppProps) {
  const router = useRouter();
  const locale: keyof typeof messages =
    (router.locale as keyof typeof messages) ?? "en-US";
  const dir = getDirection(locale);
  const cache = createCache(options[dir]);

  return (
    <IntlProvider locale={locale} messages={messages[locale]}>
      <UserProvider>
        <ApolloProvider client={client}>
          <ChakraProvider theme={theme}>
            <CacheProvider value={cache}>
              <Head>
                <title>Superstar Squad</title>
                <meta
                  name="description"
                  content="Generated by create next app"
                />
                <meta
                  name="viewport"
                  content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/logo.png" />
              </Head>
              <main className={font.className} dir={dir}>
                <Layout>
                  <Component {...pageProps} />
                </Layout>
              </main>
            </CacheProvider>
          </ChakraProvider>
        </ApolloProvider>
      </UserProvider>
    </IntlProvider>
  );
}
